services:
  # FastAPI application
  app:
    build: .
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fastapi
      - SEAWEEDFS_MASTER_URL=http://seaweedfs-master:9333
      - SEAWEEDFS_VOLUME_URL=http://localhost:8080
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_BUCKET_NAME=images-bucket
    depends_on:
      db:
        condition: service_healthy
      seaweedfs-master:
        condition: service_started
      seaweedfs-volume:
        condition: service_started
      localstack:
        condition: service_healthy

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    container_name: fastapi-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # SeaweedFS master
  seaweedfs-master:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-master
    ports:
      - "9333:9333"
      - "19333:19333"
    command: "master -ip=seaweedfs-master -port=9333"
    

  # SeaweedFS volume
  seaweedfs-volume:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-volume
    ports:
      - "8080:8080"
      - "18080:18080"
    command: "volume -max=5 -mserver=seaweedfs-master:9333 -port=8080 -ip=seaweedfs-volume -dir=/data -max=5"
    depends_on:
      - seaweedfs-master
    volumes:
      - seaweedfs_data:/data

  # LocalStack (S3)
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  seaweedfs_data:
  localstack_data: