version: '3.8'

services:
  # FastAPI application
  app:
    build: .
    container_name: fastapi-app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/fastapi
      - SEAWEEDFS_MASTER_URL=http://seaweedfs-master:9333
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_BUCKET_NAME=images-bucket
    depends_on:
      - db
      - seaweedfs-master
      - seaweedfs-volume
      - localstack

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    container_name: fastapi-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # SeaweedFS master
  seaweedfs-master:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-master
    ports:
      - "9333:9333"
      - "19333:19333"
    command: "master -ip=seaweedfs-master"

  # SeaweedFS volume
  seaweedfs-volume:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-volume
    ports:
      - "8080:8080"
      - "18080:18080"
    command: "volume -max=5 -mserver=seaweedfs-master:9333 -port=8080 -ip=seaweedfs-volume"
    depends_on:
      - seaweedfs-master
    volumes:
      - seaweedfs_data:/data

  # LocalStack (S3)
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack_data:/tmp/localstack

volumes:
  postgres_data:
  seaweedfs_data:
  localstack_data: