"""make_process_error_nullable_in_images

Revision ID: bd2238adf3cb
Revises: 769d625383c7
Create Date: 2025-07-22 09:28:52.168451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2238adf3cb'
down_revision = '769d625383c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'process_error',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'process_error',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
