"""Make storage fields nullable in images

Revision ID: bde3add3fcbb
Revises: 0db2e8dd572e
Create Date: 2025-07-22 08:28:19.734469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde3add3fcbb'
down_revision = '0db2e8dd572e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'file_path',
               existing_type=sa.String(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'file_path',
               existing_type=sa.String(length=255),
               nullable=False)
    # ### end Alembic commands ###
