"""Make thumbnail storage fields nullable

Revision ID: c1be9530c3b2
Revises: cce8f220507a
Create Date: 2025-07-22 18:05:12.862119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1be9530c3b2'
down_revision = 'cce8f220507a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thumbnails', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('thumbnails', 'storage_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('thumbnails', 'seaweedfs_fid',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('thumbnails', 's3_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('thumbnails', 's3_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thumbnails', 's3_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('thumbnails', 's3_key',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('thumbnails', 'seaweedfs_fid',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('thumbnails', 'storage_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('thumbnails', 'file_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
