name: Code Quality

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run ruff (lint)
      #   run: ruff check . --fix

      # - name: Run black (check only)
      #   run: black --check .

      # - name: Run isort (check only)
      #   run: isort . --check-only

      # - name: Run mypy
      #   run: mypy .

      - name: Run pylint
        run: |
          find . -name "*.py" | xargs pylint --disable=R,C