name: Code Quality

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black isort mypy pylint

      - name: Run Ruff (lint + fixable)
        run: ruff check . --fix

      - name: Run Black (format check)
        run: black --check .

      - name: Run Isort (import order check)
        run: isort . --check-only

      - name: Run MyPy (type checking)
        run: mypy .
